export const projects = [
  {
    title: 'Pumpushka',
    category: 'Crypto Bot Landing',
    desc: 'Crypto trading assistant bot combining technical, sentimental, macro, and on-chain analysis with whale tracking to generate high-probability market signals.',
    image: '/img/pumpushka.png',
    date: '07.07.2025',
    link: 'https://www.pumpushka.win/',
    stack: ['Astro.js', 'TinaCMS', 'Tailwind CSS'],
    starred: true,
  },
  {
    title: 'Freight-Synergy',
    category: 'Logistics services catalogue',
    desc: 'Connecting global logistics services to drive freight strategies. A platform and catalogue designed to organize and streamline freight data and business networking.',
    image: '/img/freight-synergy.png',
    date: '09.12.2024',
    link: 'https://freightsynergy.net/',
    stack: ['WordPress', 'PHP', 'SCSS', 'JavaScript'],
    starred: null,
  },
  {
    title: 'Shlyah',
    category: 'Charity Foundation',
    desc: 'Charity foundation website providing humanitarian aid, support programs, and community initiatives with modern content management and high-performance delivery.',
    image: '/img/shlyah.png',
    date: '15.01.2025',
    link: 'https://192.3.254.164.nip.io/',
    stack: ['Nuxt 3', 'Strapi 5', 'Tailwind CSS'],
    starred: true,
  },
  {
    title: 'Le Rhone',
    category: 'Promo site',
    desc: 'Geneva’s premium workplace experience: Spectacular Views, Premium Amenities, Ultimate Experience',
    image: '/img/le-rhone.png',
    date: '21.11.2022',
    link: 'https://le-rhone.ch/',
    stack: ['ESbuild', 'SmartGrid', 'Twig.js', 'Splide'],
    starred: null,
  },
  {
    title: 'Libkin',
    category: 'Personal site + eCommerce',
    desc: 'The Savva Libkin Restaurants Company, are a fine-tuning company born in Odessa. Develop concept restaurants, own food production and multi-channel models of its sale.',
    image: '/img/libkin.png',
    date: '30.09.2020',
    link: 'https://savva-libkin.com/',
    stack: ['Vue.js', 'Laravel', 'SCSS', 'Blade'],
    starred: null,
  },
  {
    title: 'Originale',
    category: 'Personal site',
    desc: 'Satirical concomitant to the understanding of art in the European Capital of Culture.',
    image: '/img/deroriginale.png',
    date: '01.08.2021',
    link: 'https://www.deroriginale.at/',
    stack: ['Jekyll', 'PWA', 'SCSS', 'Forestry.io'],
    starred: null,
  },
  {
    title: 'Verticite',
    category: 'Design & Architecture',
    desc: 'V|A is an architectural practice in Geneva, which emerged from Knight Frank Switzerland in 2020.',
    image: '/img/va.png',
    date: '20.02.2023',
    link: 'https://verticite.ch/',
    stack: ['Wordpress', 'Gulp 4', 'Bootstrap 4'],
    starred: null,
  },
];
